# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'PlantMedic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlantMedic
  pod 'SwiftLint', '~> 0.59'
  pod 'SwiftFormat/CLI'

  target 'PlantMedicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlantMedicUITests' do
    # Pods for testing
  end

end
